### ISSUE TITLE
How to send buttons?

### ISSUE THREAD

**Issue by webnetindia** [devlikeapro/whatsapp-http-api#20]
Can you give example of the json code via which we can send buttons along with a text?

Thanks for all the work and effort you have done till date :)

**Comment by allburov** [comment]
@webnetindia 

Hi! Thank you for your kind words!

I think this works if you send it as body to `POST /api/sendTextButtons` 
```yaml
{
  "sessionName": "default",
  "chatId": "123123123@c.us",
  "text": "Text",
  "title": "string",
  "buttons": [
    {
      "buttonText": {
        "displayText": "Text of Button 1"
      }
    },
    {
      "buttonText": {
        "displayText": "Text of Button 2"
      }
    }
  ]
}
```

Let me know if it does or does not!
